image: node:16-bullseye

stages:
  - install
  - test


install:
  stage: install
  script:
    - npm ci

test:
  stage: test
  before_script:
    - apt-get update
    - wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
    - apt install -y ./google-chrome*.deb
    - export CHROME_BIN=/usr/bin/google-chrome --no-sandbox
  script :
    - npm ci
    - npm run test -- --watch=false --browsers=ChromeHeadless